import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from 'next/font/local'
import "./globals.css";
import { NextFont } from "next/dist/compiled/@next/font";

const inter = Inter({ subsets: ["latin"] });
const agatho = localFont({
  src: "./font/Agatho_ Light.otf",
  variable: "--font-agatho"
})
const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${agatho.variable}`}>{children}</body>
    </html>
  );
}
