import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from 'next/font/local'
import "./globals.css";
import { NextFont } from "next/dist/compiled/@next/font";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Providers from "@/components/Providers";
import { getPhoneOnly } from "@/lib/actions";

const inter = Inter({ subsets: ["latin"] });
const agatho = localFont({
  src: "./font/Agatho_ Light.otf",
  variable: "--font-agatho"
})
const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const phoneNumber = await getPhoneOnly();
  return (
    <html lang="en">
      <body className={`${inter.className} ${agatho.variable}`}>
        <Providers>
          <Header />
          {children}

          <Footer phoneNumber={phoneNumber} />
        </Providers>
      </body>
    </html>
  );
}
